import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function json(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

// ═══════════════════════════════════════════════════════════
//  Lender Financing Agreement — PDF Generator
//  Pure text-based PDF construction (no external deps)
// ═══════════════════════════════════════════════════════════

class LenderContractPDF {
  private objects: string[] = [];
  private content: string[] = [];
  private pages: number[] = [];
  private pageCount = 0;
  private currentY = 750;

  private brandGreen = "0.086 0.396 0.204";
  private brandDark = "0.1 0.1 0.1";

  private addObject(content: string): number {
    this.objects.push(content);
    return this.objects.length;
  }

  private escapeText(text: string): string {
    return text
      .replace(/\\/g, "\\\\")
      .replace(/\(/g, "\\(")
      .replace(/\)/g, "\\)")
      .replace(/[^\x20-\x7E]/g, "?");
  }

  private drawText(text: string, x: number, y: number, size: number, bold = false): void {
    const font = bold ? "/F2" : "/F1";
    this.content.push(`BT ${font} ${size} Tf ${x} ${y} Td (${this.escapeText(text)}) Tj ET`);
  }

  private drawColorText(text: string, x: number, y: number, size: number, color: string, bold = false): void {
    const font = bold ? "/F2" : "/F1";
    this.content.push(`BT ${font} ${size} Tf ${color} rg ${x} ${y} Td (${this.escapeText(text)}) Tj 0 0 0 rg ET`);
  }

  private drawLine(x1: number, y1: number, x2: number, y2: number, width = 1, color = "0 0 0"): void {
    this.content.push(`${color} RG ${width} w ${x1} ${y1} m ${x2} ${y2} l S`);
  }

  private drawRect(x: number, y: number, w: number, h: number, fill: string): void {
    this.content.push(`${fill} rg ${x} ${y} ${w} ${h} re f`);
  }

  private drawRow(label: string, value: string, y: number): number {
    this.drawText(label, 60, y, 10);
    this.drawText(value, 280, y, 10, true);
    this.drawLine(60, y - 4, 535, y - 4, 0.5, "0.9 0.9 0.9");
    return y - 20;
  }

  private checkPage(): void {
    if (this.currentY < 100) {
      this.newPage();
      this.currentY = 750;
    }
  }

  private newPage(): void {
    if (this.content.length > 0) this.finalizePage();
    this.content = [];
    this.currentY = 750;
    this.pageCount++;
  }

  private finalizePage(): void {
    const stream = this.content.join("\n");
    const streamObj = this.addObject(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);
    const pageObj = this.addObject(
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents ${streamObj} 0 R /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> >>`
    );
    this.pages.push(pageObj);
  }

  private drawHeader(lenderName: string): void {
    // Green header bar
    this.drawRect(0, 800, 595, 42, this.brandGreen);
    this.content.push("BT /F2 14 Tf 1 1 1 rg 60 814 Td (FINANCING AGREEMENT) Tj 0 0 0 rg ET");
    this.content.push(`BT /F1 9 Tf 1 1 1 rg 60 802 Td (Issued by ${this.escapeText(lenderName)} via TrustLock Escrow Platform) Tj 0 0 0 rg ET`);

    // Watermark
    this.content.push("q 0.95 0.96 0.95 rg");
    this.content.push("BT /F2 60 Tf 150 400 Td 45 Tz 0.93 0.94 0.93 rg 30 Tr (TrustLock) Tj ET");
    this.content.push("Q");
  }

  private drawSection(title: string): void {
    this.checkPage();
    this.currentY -= 10;
    this.drawRect(55, this.currentY - 2, 480, 16, "0.96 0.97 0.96");
    this.drawColorText(title.toUpperCase(), 60, this.currentY, 9, this.brandGreen, true);
    this.currentY -= 24;
  }

  private drawParagraph(text: string, indent = 60): void {
    // Simple word-wrap at ~80 chars
    const maxWidth = 75;
    const words = text.split(" ");
    let line = "";
    for (const word of words) {
      if ((line + " " + word).length > maxWidth && line.length > 0) {
        this.checkPage();
        this.drawText(line.trim(), indent, this.currentY, 9);
        this.currentY -= 14;
        line = word;
      } else {
        line = line ? line + " " + word : word;
      }
    }
    if (line.trim()) {
      this.checkPage();
      this.drawText(line.trim(), indent, this.currentY, 9);
      this.currentY -= 14;
    }
  }

  private drawFooter(docId: string): void {
    this.drawLine(60, 55, 535, 55, 0.5, "0.8 0.8 0.8");
    this.drawText(`Document ID: ${docId}`, 60, 42, 7);
    this.drawText(`Generated by TrustLock  |  ${new Date().toISOString().slice(0, 10)}`, 60, 32, 7);
    this.drawText("Retained for 7 years per compliance policy  |  Blockchain-anchored", 60, 22, 7);
  }

  private build(): Uint8Array {
    if (this.content.length > 0) this.finalizePage();

    const fontHelvetica = this.addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
    const fontHelveticaBold = this.addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");

    // Reassign font objects to positions 3 and 4
    // Build PDF bytes
    let pdf = "%PDF-1.4\n";
    const offsets: number[] = [];

    // Object 1: Catalog
    offsets.push(pdf.length);
    pdf += "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n";

    // Object 2: Pages
    offsets.push(pdf.length);
    const pageRefs = this.pages.map((p) => `${p} 0 R`).join(" ");
    pdf += `2 0 obj\n<< /Type /Pages /Kids [${pageRefs}] /Count ${this.pages.length} >>\nendobj\n`;

    // Object 3: Font Helvetica
    offsets.push(pdf.length);
    pdf += "3 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n";

    // Object 4: Font Helvetica-Bold
    offsets.push(pdf.length);
    pdf += "4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj\n";

    // Remaining objects
    for (let i = 0; i < this.objects.length; i++) {
      offsets.push(pdf.length);
      pdf += `${i + 5} 0 obj\n${this.objects[i]}\nendobj\n`;
    }

    const totalObjs = 4 + this.objects.length;
    const xrefOffset = pdf.length;
    pdf += `xref\n0 ${totalObjs + 1}\n0000000000 65535 f \n`;
    for (const off of offsets) {
      pdf += `${String(off).padStart(10, "0")} 00000 n \n`;
    }
    pdf += `trailer\n<< /Size ${totalObjs + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

    return new TextEncoder().encode(pdf);
  }

  generate(meta: {
    lenderName: string;
    lenderType: string;
    vendorName: string;
    approvedAmount: number;
    interestRate: number;
    tenureDays: number;
    applicationId: string;
    items?: Array<{ description: string; quantity: number; unit_price_usd: number }>;
    milestones?: string;
    governingLaw?: string;
  }): Uint8Array {
    const docId = `LC-${meta.applicationId.slice(0, 8).toUpperCase()}`;
    const today = new Date().toISOString().slice(0, 10);
    const maturityDate = new Date();
    maturityDate.setDate(maturityDate.getDate() + (meta.tenureDays || 90));

    // ─── Page 1: Agreement Header ───
    this.newPage();
    this.drawHeader(meta.lenderName);

    this.currentY = 770;
    this.drawText("FINANCING AGREEMENT", 60, this.currentY, 16, true);
    this.currentY -= 20;
    this.drawText(`Between ${meta.lenderName} ("Lender") and ${meta.vendorName} ("Borrower")`, 60, this.currentY, 9);
    this.currentY -= 30;

    this.drawSection("Agreement Details");
    this.currentY = this.drawRow("Agreement Reference", docId, this.currentY);
    this.currentY = this.drawRow("Lender", meta.lenderName, this.currentY);
    this.currentY = this.drawRow("Institution Type", meta.lenderType || "N/A", this.currentY);
    this.currentY = this.drawRow("Borrower (Vendor)", meta.vendorName, this.currentY);
    this.currentY = this.drawRow("Agreement Date", today, this.currentY);
    this.currentY = this.drawRow("Application ID", meta.applicationId.slice(0, 8) + "...", this.currentY);

    this.drawSection("Financial Terms");
    this.currentY = this.drawRow("Principal Amount", `$${meta.approvedAmount.toLocaleString()}`, this.currentY);
    this.currentY = this.drawRow("Interest Rate", `${meta.interestRate}% per annum`, this.currentY);
    this.currentY = this.drawRow("Tenure", `${meta.tenureDays} days`, this.currentY);
    this.currentY = this.drawRow("Maturity Date", maturityDate.toISOString().slice(0, 10), this.currentY);
    const totalRepayment = meta.approvedAmount * (1 + (meta.interestRate / 100) * (meta.tenureDays / 365));
    this.currentY = this.drawRow("Total Repayment (est.)", `$${totalRepayment.toFixed(2)}`, this.currentY);

    // ─── Itemized Schedule (if present) ───
    if (meta.items && meta.items.length > 0) {
      this.drawSection("Itemized Funding Schedule");
      // Table header
      this.drawText("Description", 60, this.currentY, 8, true);
      this.drawText("Qty", 320, this.currentY, 8, true);
      this.drawText("Unit Price", 370, this.currentY, 8, true);
      this.drawText("Subtotal", 460, this.currentY, 8, true);
      this.currentY -= 14;
      this.drawLine(60, this.currentY + 4, 535, this.currentY + 4, 0.5, "0.7 0.7 0.7");

      for (const item of meta.items) {
        this.checkPage();
        const desc = item.description.length > 40 ? item.description.slice(0, 40) + "..." : item.description;
        this.drawText(desc, 60, this.currentY, 8);
        this.drawText(String(item.quantity), 330, this.currentY, 8);
        this.drawText(`$${item.unit_price_usd.toFixed(2)}`, 370, this.currentY, 8);
        this.drawText(`$${(item.quantity * item.unit_price_usd).toFixed(2)}`, 460, this.currentY, 8);
        this.currentY -= 14;
      }
      this.drawLine(60, this.currentY + 4, 535, this.currentY + 4, 1, "0.5 0.5 0.5");
      this.drawText("Total", 60, this.currentY - 4, 9, true);
      this.drawText(`$${meta.approvedAmount.toLocaleString()}`, 460, this.currentY - 4, 9, true);
      this.currentY -= 24;
    }

    // ─── Terms & Conditions ───
    this.drawSection("Terms & Conditions");
    const terms = [
      `1. PURPOSE: The Lender agrees to provide financing of $${meta.approvedAmount.toLocaleString()} to the Borrower for the purposes described in the financing application.`,
      "2. DISBURSEMENT: Funds shall be disbursed offline by the Lender directly to the Borrower upon execution of this agreement. TrustLock acts solely as a record-keeping and escrow intermediary.",
      `3. REPAYMENT: The Borrower agrees to repay the full amount plus interest ($${totalRepayment.toFixed(2)}) within ${meta.tenureDays} days of disbursement.`,
      "4. MILESTONE TRIGGERS: Where the financing is linked to a TrustLock escrow transaction, milestone releases may serve as repayment triggers as agreed by both parties.",
      "5. DEFAULT: Failure to repay by the maturity date constitutes default. The Lender may pursue remedies under applicable law.",
      "6. ESCROW PROTECTION: Any funds held in TrustLock escrow related to transactions financed under this agreement remain subject to escrow terms and cannot be unilaterally seized.",
      "7. PLATFORM ROLE: TrustLock provides the platform for record-keeping, document archival, and optional milestone-linked repayment tracking. TrustLock is not a party to this financing agreement and bears no liability for fund movements between Lender and Borrower.",
      `8. GOVERNING LAW: This agreement is governed by the laws of ${meta.governingLaw || "the applicable jurisdiction"}.`,
      "9. AUDIT TRAIL: This agreement and all related documents are archived for a minimum of 7 years and anchored to the blockchain for integrity verification.",
    ];

    for (const term of terms) {
      this.drawParagraph(term);
      this.currentY -= 6;
    }

    // ─── Signature Page ───
    this.newPage();
    this.drawHeader(meta.lenderName);
    this.currentY = 770;
    this.drawText("SIGNATURE PAGE", 60, this.currentY, 14, true);
    this.currentY -= 30;

    this.drawSection("Lender Signature");
    this.drawLine(60, this.currentY, 300, this.currentY, 1, "0.3 0.3 0.3");
    this.currentY -= 14;
    this.drawText("Signature", 60, this.currentY, 8);
    this.currentY -= 30;
    this.drawLine(60, this.currentY, 300, this.currentY, 1, "0.3 0.3 0.3");
    this.currentY -= 14;
    this.drawText("Name", 60, this.currentY, 8);
    this.currentY -= 30;
    this.drawLine(60, this.currentY, 300, this.currentY, 1, "0.3 0.3 0.3");
    this.currentY -= 14;
    this.drawText("Title / Position", 60, this.currentY, 8);
    this.currentY -= 30;
    this.drawLine(60, this.currentY, 300, this.currentY, 1, "0.3 0.3 0.3");
    this.currentY -= 14;
    this.drawText("Date", 60, this.currentY, 8);
    this.currentY -= 20;
    this.drawText(`On behalf of: ${meta.lenderName}`, 60, this.currentY, 9, true);

    this.currentY -= 50;

    this.drawSection("Borrower (Vendor) Signature");
    this.drawLine(60, this.currentY, 300, this.currentY, 1, "0.3 0.3 0.3");
    this.currentY -= 14;
    this.drawText("Signature", 60, this.currentY, 8);
    this.currentY -= 30;
    this.drawLine(60, this.currentY, 300, this.currentY, 1, "0.3 0.3 0.3");
    this.currentY -= 14;
    this.drawText("Name", 60, this.currentY, 8);
    this.currentY -= 30;
    this.drawLine(60, this.currentY, 300, this.currentY, 1, "0.3 0.3 0.3");
    this.currentY -= 14;
    this.drawText("Title / Position", 60, this.currentY, 8);
    this.currentY -= 30;
    this.drawLine(60, this.currentY, 300, this.currentY, 1, "0.3 0.3 0.3");
    this.currentY -= 14;
    this.drawText("Date", 60, this.currentY, 8);
    this.currentY -= 20;
    this.drawText(`On behalf of: ${meta.vendorName}`, 60, this.currentY, 9, true);

    this.drawFooter(docId);
    return this.build();
  }
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const body = await req.json();
    const { application_id } = body;

    if (!application_id) {
      return json({ error: "application_id is required" }, 400);
    }

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    // Fetch application with related data
    const { data: app, error: appError } = await supabase
      .from("financing_applications")
      .select(`
        *,
        financing_application_items (*)
      `)
      .eq("id", application_id)
      .single();

    if (appError || !app) {
      return json({ error: "Application not found" }, 404);
    }

    // Fetch lender profile
    const { data: lender } = await supabase
      .from("lender_profiles")
      .select("institution_name, institution_type, logo_url")
      .eq("user_id", app.lender_id)
      .single();

    // Fetch vendor profile
    const { data: vendor } = await supabase
      .from("profiles")
      .select("company_name, full_name")
      .eq("id", app.vendor_id)
      .single();

    const pdf = new LenderContractPDF();
    const pdfBytes = pdf.generate({
      lenderName: lender?.institution_name || "Lender",
      lenderType: lender?.institution_type || "N/A",
      vendorName: vendor?.company_name || vendor?.full_name || "Vendor",
      approvedAmount: app.approved_amount || app.requested_amount,
      interestRate: app.interest_rate_percent || 0,
      tenureDays: app.approved_tenure_days || 90,
      applicationId: app.id,
      items: app.financing_application_items || [],
      governingLaw: app.proposed_terms?.governing_law,
    });

    // Upload to protection-documents bucket
    const fileName = `lender-contracts/${application_id}/financing-agreement.pdf`;
    const { error: uploadError } = await supabase.storage
      .from("protection-documents")
      .upload(fileName, pdfBytes, {
        contentType: "application/pdf",
        upsert: true,
      });

    if (uploadError) {
      console.error("Upload error:", uploadError);
      return json({ error: "Failed to upload contract PDF" }, 500);
    }

    // Get signed URL
    const { data: urlData } = await supabase.storage
      .from("protection-documents")
      .createSignedUrl(fileName, 60 * 60 * 24 * 365); // 1 year

    // Archive in protection_documents table
    await supabase.from("protection_documents").insert({
      document_type: "financing_agreement",
      title: `Financing Agreement — ${application_id.slice(0, 8)}`,
      transaction_id: app.transaction_id,
      user_id: app.vendor_id,
      role: "lender",
      industry: app.industry,
      retention_years: 7,
      file_url: urlData?.signedUrl || fileName,
      metadata: {
        application_id,
        lender_id: app.lender_id,
        vendor_id: app.vendor_id,
        approved_amount: app.approved_amount,
        auto_generated: true,
      },
    });

    // Notify both parties
    await supabase.from("notifications").insert([
      {
        user_id: app.vendor_id,
        type: "financing_contract_generated",
        title: "Financing Agreement Generated",
        message: "Your financing agreement is ready for review and signing.",
        data: { application_id },
      },
      {
        user_id: app.lender_id,
        type: "financing_contract_generated",
        title: "Financing Agreement Generated",
        message: `Agreement for $${(app.approved_amount || app.requested_amount).toLocaleString()} is ready.`,
        data: { application_id },
      },
    ]);

    return json({
      success: true,
      pdf_url: urlData?.signedUrl || fileName,
      document_id: `LC-${application_id.slice(0, 8).toUpperCase()}`,
    });
  } catch (err) {
    return json({ success: false, error: err.message }, 400);
  }
});
