import { useState } from "react";
import { cn } from "@/lib/utils";
import { useBlockchainAnchor, type ProofRecord } from "@/hooks/useBlockchainAnchor";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Shield, Download, Loader2, CheckCircle2, FileText, Hash } from "lucide-react";
import { toast } from "sonner";

const RECORD_LABELS: Record<string, string> = {
  invoice: "Invoice",
  contract: "Contract",
  signature: "Digital Signature",
  milestone: "Milestone Completion",
  observer_signoff: "Observer Sign-Off",
  dispute_ruling: "Dispute Ruling",
  document_upload: "Document Upload",
  acknowledgement: "Acknowledgement",
  payout: "Fund Release/Refund",
  aml_screening: "AML Screening",
  gps_verification: "GPS Verification",
  price_lock: "Price Lock",
  rejection: "Rejection",
  hash_chain_anchor: "Chain Checkpoint",
};

interface ProofCertificateProps {
  transactionId: string;
  orderNumber?: string;
  className?: string;
}

const ProofCertificate = ({ transactionId, orderNumber, className }: ProofCertificateProps) => {
  const { getProofsByTransaction, loading } = useBlockchainAnchor();
  const [generating, setGenerating] = useState(false);

  const generateCertificate = async () => {
    setGenerating(true);
    try {
      const proofs = await getProofsByTransaction(transactionId);

      if (proofs.length === 0) {
        toast.error("No blockchain proofs found for this transaction");
        return;
      }

      // Verify chain integrity
      let chainValid = true;
      for (let i = 1; i < proofs.length; i++) {
        if (proofs[i].prev_hash !== proofs[i - 1].content_hash) {
          chainValid = false;
          break;
        }
      }

      // Generate text-based certificate (no external PDF lib needed)
      const lines: string[] = [];
      lines.push("═══════════════════════════════════════════════════════════════");
      lines.push("             TRUSTLOCK BLOCKCHAIN PROOF CERTIFICATE           ");
      lines.push("═══════════════════════════════════════════════════════════════");
      lines.push("");
      lines.push(`  Order:          ${orderNumber || "N/A"}`);
      lines.push(`  Transaction ID: ${transactionId}`);
      lines.push(`  Generated:      ${new Date().toISOString()}`);
      lines.push(`  Total Proofs:   ${proofs.length}`);
      lines.push(`  Chain Integrity: ${chainValid ? "✓ VALID" : "✗ BROKEN"}`);
      lines.push("");
      lines.push("───────────────────────────────────────────────────────────────");
      lines.push("  PROOF CHAIN RECORDS");
      lines.push("───────────────────────────────────────────────────────────────");

      proofs.forEach((proof, i) => {
        lines.push("");
        lines.push(`  Record #${i + 1}: ${RECORD_LABELS[proof.record_type] || proof.record_type}`);
        lines.push(`  ─────────────────────────────────────────────────`);
        lines.push(`  Content Hash:  ${proof.content_hash}`);
        lines.push(`  Previous Hash: ${proof.prev_hash}`);
        lines.push(`  Chain Status:  ${proof.chain_status}`);
        lines.push(`  Timestamp:     ${proof.created_at}`);
        if (proof.polygon_tx_hash) {
          lines.push(`  Polygon TX:    ${proof.polygon_tx_hash}`);
          lines.push(`  Verify:        https://polygonscan.com/tx/${proof.polygon_tx_hash}`);
        }
        if (proof.event_data && Object.keys(proof.event_data).length > 0) {
          lines.push(`  Event Data:`);
          Object.entries(proof.event_data).forEach(([key, value]) => {
            const val = typeof value === "object" ? JSON.stringify(value) : String(value);
            lines.push(`    ${key}: ${val}`);
          });
        }
      });

      lines.push("");
      lines.push("───────────────────────────────────────────────────────────────");
      lines.push("  VERIFICATION INSTRUCTIONS");
      lines.push("───────────────────────────────────────────────────────────────");
      lines.push("");
      lines.push("  1. Take any Content Hash above");
      lines.push("  2. Call verifyHash(contentHash) on the TrustLockRegistry contract");
      lines.push("     on Polygon network");
      lines.push("  3. The contract returns (exists=true, recordId) if valid");
      lines.push("  4. Call verifyChain(0, recordId) to confirm chain integrity");
      lines.push("");
      lines.push("  Contract: TrustLockRegistry on Polygon PoS");
      lines.push("  Standard: SHA-256 hash chain with immutable on-chain anchoring");
      lines.push("");
      lines.push("═══════════════════════════════════════════════════════════════");
      lines.push("  This certificate was generated by TrustLock (Azix Technologies)");
      lines.push("  https://trustlockpay.lovable.app");
      lines.push("═══════════════════════════════════════════════════════════════");

      // Download as text file
      const blob = new Blob([lines.join("\n")], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `TrustLock_Proof_Certificate_${orderNumber || transactionId.slice(0, 8)}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      toast.success("Proof certificate downloaded");
    } catch (err) {
      toast.error("Failed to generate certificate");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <Button
      variant="outline"
      size="sm"
      onClick={generateCertificate}
      disabled={generating || loading}
      className={cn("gap-1.5", className)}
    >
      {generating ? (
        <Loader2 className="w-3.5 h-3.5 animate-spin" />
      ) : (
        <Download className="w-3.5 h-3.5" />
      )}
      <span className="text-xs">Proof Certificate</span>
    </Button>
  );
};

export default ProofCertificate;
