import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Shield, FileText, Download, Receipt, ScrollText, Printer } from "lucide-react";

interface TransactionDoc {
  txId: string;
  vendorName: string;
  buyerName: string;
  item: string;
  amount: number;
  fee?: number;
  date: string;
  status: string;
  tracking?: string;
  industry?: string;
  taxBreakdown?: Record<string, any>;
  invoiceItems?: any[];
}

type DocType = "invoice" | "contract" | "tax";

const docMeta: Record<DocType, { label: string; icon: any; desc: string }> = {
  invoice: { label: "Invoice / Receipt", icon: FileText, desc: "Itemized order receipt" },
  contract: { label: "Pre-Order Contract", icon: ScrollText, desc: "Signed transaction contract" },
  tax: { label: "Tax Receipt", icon: Receipt, desc: "Tax & duty breakdown" },
};

const printDocument = (title: string, contentId: string) => {
  const content = document.getElementById(contentId);
  if (!content) return;
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;
  printWindow.document.write(`
    <html><head><title>${title}</title>
    <style>
      body { font-family: system-ui, sans-serif; padding: 40px; max-width: 700px; margin: auto; color: #1a1a1a; }
      .header { display: flex; align-items: center; gap: 12px; margin-bottom: 24px; padding-bottom: 16px; border-bottom: 2px solid #166534; }
      .logo { width: 40px; height: 40px; border-radius: 8px; background: #166534; display: flex; align-items: center; justify-content: center; color: white; font-weight: bold; font-size: 14px; }
      h1 { font-size: 18px; margin: 0; } h2 { font-size: 14px; margin: 16px 0 8px; color: #555; text-transform: uppercase; letter-spacing: 1px; }
      .row { display: flex; justify-content: space-between; padding: 6px 0; font-size: 13px; border-bottom: 1px solid #eee; }
      .row-label { color: #666; } .row-value { font-weight: 600; }
      .total-row { border-top: 2px solid #166534; padding-top: 8px; margin-top: 8px; font-size: 15px; }
      .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 11px; color: #888; text-align: center; }
      .item-card { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 6px; padding: 10px; margin-bottom: 6px; font-size: 12px; display: flex; justify-content: space-between; }
      @media print { body { padding: 20px; } }
    </style></head><body>${content.innerHTML}
    <div class="footer">Generated by TrustLock OS · trustlockpay.lovable.app · ${new Date().toLocaleString()}</div>
    </body></html>
  `);
  printWindow.document.close();
  printWindow.print();
};

const InvoiceView = ({ tx }: { tx: TransactionDoc }) => (
  <div id="doc-invoice">
    <div className="header" style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 24, paddingBottom: 16, borderBottom: "2px solid #166534" }}>
      <div className="logo" style={{ width: 40, height: 40, borderRadius: 8, background: "#166534", display: "flex", alignItems: "center", justifyContent: "center", color: "white", fontWeight: "bold", fontSize: 14 }}>TL</div>
      <div><h1 style={{ fontSize: 18, margin: 0 }}>Invoice / Receipt</h1><p style={{ fontSize: 12, color: "#666", margin: 0 }}>TrustLock Escrow</p></div>
    </div>
    <h2 style={{ fontSize: 14, margin: "16px 0 8px", color: "#555", textTransform: "uppercase", letterSpacing: 1 }}>Transaction Details</h2>
    <div className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}><span style={{ color: "#666" }}>Transaction ID</span><span style={{ fontWeight: 600 }}>{tx.txId}</span></div>
    <div className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}><span style={{ color: "#666" }}>Date</span><span style={{ fontWeight: 600 }}>{tx.date}</span></div>
    <div className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}><span style={{ color: "#666" }}>Vendor</span><span style={{ fontWeight: 600 }}>{tx.vendorName}</span></div>
    <div className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}><span style={{ color: "#666" }}>Buyer</span><span style={{ fontWeight: 600 }}>{tx.buyerName}</span></div>
    <div className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}><span style={{ color: "#666" }}>Item</span><span style={{ fontWeight: 600 }}>{tx.item}</span></div>
    {tx.tracking && <div className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}><span style={{ color: "#666" }}>Tracking</span><span style={{ fontWeight: 600 }}>{tx.tracking}</span></div>}
    {tx.invoiceItems && tx.invoiceItems.length > 0 && (
      <>
        <h2 style={{ fontSize: 14, margin: "16px 0 8px", color: "#555", textTransform: "uppercase", letterSpacing: 1 }}>Line Items</h2>
        {tx.invoiceItems.map((item: any, idx: number) => (
          <div key={idx} style={{ background: "#f9fafb", border: "1px solid #e5e7eb", borderRadius: 6, padding: 10, marginBottom: 6, fontSize: 12, display: "flex", justifyContent: "space-between" }}>
            <span>{item.description} (×{item.quantity})</span>
            <span style={{ fontWeight: 600 }}>${(item.quantity * item.unitPrice).toFixed(2)}</span>
          </div>
        ))}
      </>
    )}
    <h2 style={{ fontSize: 14, margin: "16px 0 8px", color: "#555", textTransform: "uppercase", letterSpacing: 1 }}>Summary</h2>
    <div className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}><span style={{ color: "#666" }}>Amount</span><span style={{ fontWeight: 600 }}>${tx.amount.toFixed(2)}</span></div>
    {(tx.fee ?? 0) > 0 && <div className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}><span style={{ color: "#666" }}>Escrow Fee</span><span style={{ fontWeight: 600 }}>${(tx.fee || 0).toFixed(2)}</span></div>}
    <div style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 15, fontWeight: 700, borderTop: "2px solid #166534", paddingTop: 8, marginTop: 8 }}><span>Total</span><span>${(tx.amount + (tx.fee || 0)).toFixed(2)}</span></div>
    <div className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}><span style={{ color: "#666" }}>Status</span><span style={{ fontWeight: 600, textTransform: "capitalize" }}>{tx.status}</span></div>
  </div>
);

const TaxView = ({ tx }: { tx: TransactionDoc }) => {
  const tb = tx.taxBreakdown || {};
  const entries = Object.entries(tb).filter(([k]) => k !== "total");
  return (
    <div id="doc-tax">
      <div className="header" style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 24, paddingBottom: 16, borderBottom: "2px solid #166534" }}>
        <div className="logo" style={{ width: 40, height: 40, borderRadius: 8, background: "#166534", display: "flex", alignItems: "center", justifyContent: "center", color: "white", fontWeight: "bold", fontSize: 14 }}>TL</div>
        <div><h1 style={{ fontSize: 18, margin: 0 }}>Tax & Duty Receipt</h1><p style={{ fontSize: 12, color: "#666", margin: 0 }}>TrustLock Escrow</p></div>
      </div>
      <div className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}><span style={{ color: "#666" }}>Transaction</span><span style={{ fontWeight: 600 }}>{tx.txId}</span></div>
      <div className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}><span style={{ color: "#666" }}>Date</span><span style={{ fontWeight: 600 }}>{tx.date}</span></div>
      <div className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}><span style={{ color: "#666" }}>Item</span><span style={{ fontWeight: 600 }}>{tx.item}</span></div>
      <div className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}><span style={{ color: "#666" }}>Order Amount</span><span style={{ fontWeight: 600 }}>${tx.amount.toFixed(2)}</span></div>
      <h2 style={{ fontSize: 14, margin: "16px 0 8px", color: "#555", textTransform: "uppercase", letterSpacing: 1 }}>Tax Breakdown</h2>
      {entries.length > 0 ? entries.map(([key, val]) => (
        <div key={key} className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}>
          <span style={{ color: "#666", textTransform: "capitalize" }}>{key.replace(/_/g, " ")}</span>
          <span style={{ fontWeight: 600 }}>${typeof val === "number" ? val.toFixed(2) : String(val)}</span>
        </div>
      )) : (
        <p style={{ fontSize: 13, color: "#888", padding: "8px 0" }}>No taxes or duties applied to this transaction.</p>
      )}
      {tb.total !== undefined && (
        <div style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 15, fontWeight: 700, borderTop: "2px solid #166534", paddingTop: 8, marginTop: 8 }}><span>Total Tax</span><span>${Number(tb.total).toFixed(2)}</span></div>
      )}
    </div>
  );
};

const ContractView = ({ tx }: { tx: TransactionDoc }) => (
  <div id="doc-contract">
    <div className="header" style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 24, paddingBottom: 16, borderBottom: "2px solid #166534" }}>
      <div className="logo" style={{ width: 40, height: 40, borderRadius: 8, background: "#166534", display: "flex", alignItems: "center", justifyContent: "center", color: "white", fontWeight: "bold", fontSize: 14 }}>TL</div>
      <div><h1 style={{ fontSize: 18, margin: 0 }}>Pre-Order Signatory Contract</h1><p style={{ fontSize: 12, color: "#666", margin: 0 }}>TrustLock Escrow</p></div>
    </div>
    <div className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}><span style={{ color: "#666" }}>Transaction</span><span style={{ fontWeight: 600 }}>{tx.txId}</span></div>
    <div className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}><span style={{ color: "#666" }}>Date</span><span style={{ fontWeight: 600 }}>{tx.date}</span></div>
    <div className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}><span style={{ color: "#666" }}>Vendor</span><span style={{ fontWeight: 600 }}>{tx.vendorName}</span></div>
    <div className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}><span style={{ color: "#666" }}>Buyer</span><span style={{ fontWeight: 600 }}>{tx.buyerName}</span></div>
    <div className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}><span style={{ color: "#666" }}>Item</span><span style={{ fontWeight: 600 }}>{tx.item}</span></div>
    <div className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}><span style={{ color: "#666" }}>Amount</span><span style={{ fontWeight: 600 }}>${tx.amount.toFixed(2)}</span></div>
    <div className="row" style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", fontSize: 13, borderBottom: "1px solid #eee" }}><span style={{ color: "#666" }}>Industry</span><span style={{ fontWeight: 600, textTransform: "capitalize" }}>{tx.industry || "General"}</span></div>
    <h2 style={{ fontSize: 14, margin: "16px 0 8px", color: "#555", textTransform: "uppercase", letterSpacing: 1 }}>Terms</h2>
    <p style={{ fontSize: 12, lineHeight: 1.6, color: "#444" }}>
      Both parties agree that the amount of ${tx.amount.toFixed(2)} shall be held in TrustLock escrow until delivery is confirmed or the 14-day auto-release window expires. Either party may file a dispute within the release window. This contract was digitally signed at checkout.
    </p>
    <div style={{ marginTop: 24, display: "flex", justifyContent: "space-between" }}>
      <div><p style={{ fontSize: 11, color: "#888" }}>Buyer Signature</p><p style={{ fontSize: 13, fontWeight: 600, borderBottom: "1px solid #333", paddingBottom: 4 }}>{tx.buyerName}</p></div>
      <div style={{ textAlign: "right" }}><p style={{ fontSize: 11, color: "#888" }}>Vendor Signature</p><p style={{ fontSize: 13, fontWeight: 600, borderBottom: "1px solid #333", paddingBottom: 4 }}>{tx.vendorName}</p></div>
    </div>
  </div>
);

interface TransactionDocumentsProps {
  tx: TransactionDoc;
  compact?: boolean;
}

const TransactionDocuments = ({ tx, compact = false }: TransactionDocumentsProps) => {
  const [openDoc, setOpenDoc] = useState<DocType | null>(null);

  const handlePrint = (type: DocType) => {
    printDocument(docMeta[type].label, `doc-${type}`);
  };

  if (compact) {
    return (
      <>
        <div className="flex gap-1.5 flex-wrap">
          {(["invoice", "contract", "tax"] as DocType[]).map((type) => {
            const meta = docMeta[type];
            return (
              <Button key={type} variant="outline" size="sm" className="text-[10px] h-7 px-2 gap-1" onClick={() => setOpenDoc(type)}>
                <meta.icon className="w-3 h-3" /> {meta.label}
              </Button>
            );
          })}
        </div>
        <Dialog open={!!openDoc} onOpenChange={() => setOpenDoc(null)}>
          <DialogContent className="max-w-lg max-h-[80vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <Shield className="w-4 h-4 text-primary" />
                {openDoc && docMeta[openDoc].label}
              </DialogTitle>
            </DialogHeader>
            <div className="space-y-4">
              {openDoc === "invoice" && <InvoiceView tx={tx} />}
              {openDoc === "contract" && <ContractView tx={tx} />}
              {openDoc === "tax" && <TaxView tx={tx} />}
              <Button className="w-full gap-2" onClick={() => openDoc && handlePrint(openDoc)}>
                <Printer className="w-4 h-4" /> Print / Save as PDF
              </Button>
            </div>
          </DialogContent>
        </Dialog>
      </>
    );
  }

  return (
    <div className="space-y-3">
      <h3 className="text-sm font-semibold flex items-center gap-2">
        <Download className="w-4 h-4 text-primary" /> Transaction Documents
        <Badge variant="secondary" className="text-[9px]">Free</Badge>
      </h3>
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
        {(["invoice", "contract", "tax"] as DocType[]).map((type) => {
          const meta = docMeta[type];
          return (
            <Card key={type} className="cursor-pointer hover:border-primary/30 transition-colors" onClick={() => setOpenDoc(type)}>
              <CardContent className="p-3 flex items-center gap-3">
                <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                  <meta.icon className="w-4 h-4 text-primary" />
                </div>
                <div className="min-w-0">
                  <p className="text-xs font-semibold truncate">{meta.label}</p>
                  <p className="text-[10px] text-muted-foreground">{meta.desc}</p>
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      <Dialog open={!!openDoc} onOpenChange={() => setOpenDoc(null)}>
        <DialogContent className="max-w-lg max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Shield className="w-4 h-4 text-primary" />
              {openDoc && docMeta[openDoc].label}
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            {openDoc === "invoice" && <InvoiceView tx={tx} />}
            {openDoc === "contract" && <ContractView tx={tx} />}
            {openDoc === "tax" && <TaxView tx={tx} />}
            <Button className="w-full gap-2" onClick={() => openDoc && handlePrint(openDoc)}>
              <Printer className="w-4 h-4" /> Print / Save as PDF
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default TransactionDocuments;
export type { TransactionDoc };
