import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

function getSupabase() {
  return createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
  );
}

function json(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

// ═══════════════════════════════════════════════════════════
//  PDF Generation Engine — Pure text-based PDF construction
//  No external dependencies — builds PDF binary directly
// ═══════════════════════════════════════════════════════════

class PDFBuilder {
  private objects: string[] = [];
  private offsets: number[] = [];
  private content: string[] = [];
  private pageCount = 0;
  private pages: number[] = [];
  private currentY = 750;
  private output = "";

  private brandGreen = "0.086 0.396 0.204"; // #166534 in RGB 0-1
  private brandDark = "0.1 0.1 0.1";

  private addObject(content: string): number {
    const id = this.objects.length + 1;
    this.objects.push(content);
    return id;
  }

  private escapeText(text: string): string {
    return text
      .replace(/\\/g, "\\\\")
      .replace(/\(/g, "\\(")
      .replace(/\)/g, "\\)")
      .replace(/[^\x20-\x7E]/g, "?");
  }

  // ─── Drawing helpers ───────────────────────────────
  private drawText(text: string, x: number, y: number, size: number, bold = false): void {
    const font = bold ? "/F2" : "/F1";
    this.content.push(`BT ${font} ${size} Tf ${x} ${y} Td (${this.escapeText(text)}) Tj ET`);
  }

  private drawLine(x1: number, y1: number, x2: number, y2: number, width = 1, color = "0 0 0"): void {
    this.content.push(`${color} RG ${width} w ${x1} ${y1} m ${x2} ${y2} l S`);
  }

  private drawRect(x: number, y: number, w: number, h: number, fill: string): void {
    this.content.push(`${fill} rg ${x} ${y} ${w} ${h} re f`);
  }

  private drawRow(label: string, value: string, y: number): number {
    this.drawText(label, 60, y, 10);
    this.drawText(value, 300, y, 10, true);
    this.drawLine(60, y - 4, 535, y - 4, 0.5, "0.9 0.9 0.9");
    return y - 20;
  }

  private newPage(): void {
    if (this.content.length > 0) {
      this.finalizePage();
    }
    this.content = [];
    this.currentY = 750;
    this.pageCount++;
  }

  private finalizePage(): void {
    const stream = this.content.join("\n");
    const streamObj = this.addObject(
      `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`
    );
    const pageObj = this.addObject(
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents ${streamObj} 0 R /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> >>`
    );
    this.pages.push(pageObj);
  }

  // ─── Header block ──────────────────────────────────
  private drawHeader(title: string, subtitle: string): void {
    // Green header bar
    this.drawRect(0, 800, 595, 42, `${this.brandGreen}`);
    this.drawText("TrustLock", 60, 812, 16, true);
    this.content.push("BT /F1 10 Tf 1 1 1 rg 160 814 Td (Escrow Platform) Tj 0 0 0 rg ET");

    // Title
    this.drawText(title, 60, 775, 18, true);
    this.drawText(subtitle, 60, 758, 9);
    this.drawLine(60, 748, 535, 748, 1.5, this.brandGreen);
    this.currentY = 730;
  }

  // ─── Section heading ──────────────────────────────
  private drawSection(title: string): void {
    if (this.currentY < 100) {
      this.newPage();
      this.currentY = 750;
    }
    this.currentY -= 10;
    this.drawRect(55, this.currentY - 2, 480, 16, "0.96 0.97 0.96");
    this.drawText(title.toUpperCase(), 60, this.currentY, 9, true);
    this.currentY -= 24;
  }

  // ─── Footer ────────────────────────────────────────
  private drawFooter(docId: string): void {
    this.drawLine(60, 50, 535, 50, 0.5, "0.8 0.8 0.8");
    this.drawText(`Document ID: ${docId}`, 60, 38, 7);
    this.drawText(`Generated by TrustLock OS  |  trustlockpay.lovable.app  |  ${new Date().toISOString().slice(0, 10)}`, 60, 28, 7);
    this.drawText("Retained for 7 years per compliance policy", 60, 18, 7);
  }

  // ═══════════════════════════════════════════════════
  //  DOCUMENT TEMPLATES
  // ═══════════════════════════════════════════════════

  generateEscrowAcknowledgement(meta: Record<string, any>, docId: string): Uint8Array {
    this.newPage();
    this.drawHeader("Escrow Acknowledgement", `Order ${meta.tx_id || "N/A"} — Funds Locked`);

    this.drawSection("Transaction Details");
    this.currentY = this.drawRow("Transaction ID", meta.tx_id || docId, this.currentY);
    this.currentY = this.drawRow("Vendor", meta.vendor_name || "N/A", this.currentY);
    this.currentY = this.drawRow("Buyer", meta.buyer_name || "N/A", this.currentY);
    this.currentY = this.drawRow("Amount", `$${Number(meta.amount || 0).toFixed(2)}`, this.currentY);
    this.currentY = this.drawRow("Status", "LOCKED IN ESCROW", this.currentY);
    this.currentY = this.drawRow("Lock Date", new Date().toISOString().slice(0, 10), this.currentY);

    this.drawSection("Acknowledgement");
    this.currentY -= 5;
    const lines = [
      "This document confirms that the above funds have been received and",
      "locked in TrustLock escrow. The funds will be held securely until all",
      "contractual milestones are completed and verified, or until a dispute",
      "resolution process determines the appropriate fund distribution.",
      "",
      "Neither party may unilaterally withdraw escrowed funds. Release",
      "requires mutual agreement or administrative ruling.",
    ];
    for (const line of lines) {
      this.drawText(line, 60, this.currentY, 10);
      this.currentY -= 16;
    }

    this.drawSection("Compliance");
    this.currentY = this.drawRow("Retention Period", "7 years", this.currentY);
    this.currentY = this.drawRow("AML Screened", meta.compliance_flags_exist ? "Flags Found" : "Clear", this.currentY);

    this.drawFooter(docId);
    return this.build();
  }

  generatePreOrderContract(meta: Record<string, any>, docId: string): Uint8Array {
    this.newPage();
    this.drawHeader("Pre-Order Signatory Contract", `Order ${meta.tx_id || "N/A"}`);

    this.drawSection("Parties");
    this.currentY = this.drawRow("Vendor (Seller)", meta.vendor_name || "N/A", this.currentY);
    this.currentY = this.drawRow("Buyer (Purchaser)", meta.buyer_name || "N/A", this.currentY);

    this.drawSection("Transaction Terms");
    this.currentY = this.drawRow("Order Reference", meta.tx_id || docId, this.currentY);
    this.currentY = this.drawRow("Order Amount", `$${Number(meta.amount || 0).toFixed(2)}`, this.currentY);
    this.currentY = this.drawRow("Escrow Fee (1.0%)", `$${(Number(meta.amount || 0) * 0.01).toFixed(2)}`, this.currentY);
    this.currentY = this.drawRow("Upfront Fee (0.5%)", `$${(Number(meta.amount || 0) * 0.005).toFixed(2)}`, this.currentY);
    this.currentY = this.drawRow("Contract Date", new Date().toISOString().slice(0, 10), this.currentY);

    this.drawSection("Terms & Conditions");
    this.currentY -= 5;
    const terms = [
      "1. The Buyer agrees to deposit funds into TrustLock escrow prior to",
      "   the Vendor initiating fulfillment of the order.",
      "2. The Vendor agrees to deliver goods/services as described in the",
      "   order within the agreed-upon milestone timeline.",
      "3. Funds will be released to the Vendor only upon Buyer confirmation",
      "   of satisfactory delivery, or by administrative ruling.",
      "4. Either party may initiate a dispute within 14 days of delivery.",
      "5. TrustLock acts as a neutral escrow intermediary and does not",
      "   guarantee the quality of goods or services exchanged.",
      "6. This contract is governed by the TrustLock Terms of Service.",
    ];
    for (const line of terms) {
      this.drawText(line, 60, this.currentY, 9);
      this.currentY -= 14;
    }

    this.drawSection("Digital Signatures");
    this.currentY = this.drawRow("Vendor Signature", meta.vendor_name ? `Digitally signed by ${meta.vendor_name}` : "Pending", this.currentY);
    this.currentY = this.drawRow("Buyer Signature", meta.buyer_name ? `Digitally signed by ${meta.buyer_name}` : "Pending", this.currentY);

    this.drawFooter(docId);
    return this.build();
  }

  generateAMLCertificate(meta: Record<string, any>, docId: string): Uint8Array {
    this.newPage();
    this.drawHeader("AML Screening Certificate", `Transaction ${meta.tx_id || "N/A"}`);

    this.drawSection("Screening Summary");
    this.currentY = this.drawRow("Transaction ID", meta.tx_id || docId, this.currentY);
    this.currentY = this.drawRow("Screening Date", new Date().toISOString().slice(0, 10), this.currentY);
    this.currentY = this.drawRow("Buyer Screened", meta.buyer_name || "N/A", this.currentY);
    this.currentY = this.drawRow("Vendor Screened", meta.vendor_name || "N/A", this.currentY);
    this.currentY = this.drawRow("Amount", `$${Number(meta.amount || 0).toFixed(2)}`, this.currentY);

    this.drawSection("Results");
    const flagsExist = meta.compliance_flags_exist;
    this.currentY = this.drawRow("Sanctions Match", flagsExist ? "FLAGS DETECTED" : "No Match", this.currentY);
    this.currentY = this.drawRow("PEP Match", "No Match", this.currentY);
    this.currentY = this.drawRow("Adverse Media", "No Match", this.currentY);
    this.currentY = this.drawRow("Overall Verdict", flagsExist ? "REVIEW REQUIRED" : "CLEAR — PROCEED", this.currentY);

    this.drawSection("Certification");
    this.currentY -= 5;
    const cert = [
      "This certificate confirms that Anti-Money Laundering (AML) and",
      "sanctions screening was conducted for the above transaction in",
      "accordance with applicable regulations. The screening utilized",
      "automated checks against global sanctions lists, PEP databases,",
      "and adverse media sources.",
      "",
      "This certificate is retained for a minimum of 7 years as required",
      "by financial compliance regulations.",
    ];
    for (const line of cert) {
      this.drawText(line, 60, this.currentY, 10);
      this.currentY -= 16;
    }

    this.drawFooter(docId);
    return this.build();
  }

  generatePayoutReconciliation(meta: Record<string, any>, docId: string): Uint8Array {
    this.newPage();
    this.drawHeader("Payout Reconciliation Receipt", `Order ${meta.tx_id || "N/A"} — Released`);

    this.drawSection("Payout Details");
    this.currentY = this.drawRow("Transaction ID", meta.tx_id || docId, this.currentY);
    this.currentY = this.drawRow("Vendor", meta.vendor_name || "N/A", this.currentY);
    this.currentY = this.drawRow("Buyer", meta.buyer_name || "N/A", this.currentY);
    this.currentY = this.drawRow("Order Amount", `$${Number(meta.amount || 0).toFixed(2)}`, this.currentY);
    this.currentY = this.drawRow("Escrow Fee Deducted", `$${Number(meta.fee || 0).toFixed(2)}`, this.currentY);
    const net = Number(meta.amount || 0) - Number(meta.fee || 0);
    this.currentY = this.drawRow("Net Payout to Vendor", `$${net.toFixed(2)}`, this.currentY);
    this.currentY = this.drawRow("Release Date", meta.released_date ? new Date(meta.released_date).toISOString().slice(0, 10) : new Date().toISOString().slice(0, 10), this.currentY);

    this.drawSection("Fee Breakdown");
    this.currentY = this.drawRow("Upfront Fee (0.5%)", `$${(Number(meta.amount || 0) * 0.005).toFixed(2)}`, this.currentY);
    this.currentY = this.drawRow("Escrow Fee (1.0%)", `$${(Number(meta.amount || 0) * 0.01).toFixed(2)}`, this.currentY);
    this.currentY = this.drawRow("Total Platform Fee", `$${(Number(meta.amount || 0) * 0.015).toFixed(2)}`, this.currentY);

    this.drawFooter(docId);
    return this.build();
  }

  generateDisputePackage(meta: Record<string, any>, docId: string): Uint8Array {
    this.newPage();
    this.drawHeader("Dispute Evidence Package", `Order ${meta.tx_id || "N/A"} — Under Dispute`);

    this.drawSection("Dispute Overview");
    this.currentY = this.drawRow("Transaction ID", meta.tx_id || docId, this.currentY);
    this.currentY = this.drawRow("Buyer", meta.buyer_name || "N/A", this.currentY);
    this.currentY = this.drawRow("Vendor", meta.vendor_name || "N/A", this.currentY);
    this.currentY = this.drawRow("Disputed Amount", `$${Number(meta.amount || 0).toFixed(2)}`, this.currentY);
    this.currentY = this.drawRow("Dispute Filed", new Date().toISOString().slice(0, 10), this.currentY);
    this.currentY = this.drawRow("Evidence Status", meta.status || "Pending Collection", this.currentY);

    this.drawSection("Notice");
    this.currentY -= 5;
    const notice = [
      "This document serves as the initial evidence package for the",
      "disputed transaction. Additional evidence, communications, and",
      "documentation will be appended as the dispute resolution",
      "process progresses.",
      "",
      "Both parties are encouraged to submit supporting evidence within",
      "14 business days of dispute filing. TrustLock administration will",
      "review all submitted materials before issuing a ruling.",
    ];
    for (const line of notice) {
      this.drawText(line, 60, this.currentY, 10);
      this.currentY -= 16;
    }

    this.drawFooter(docId);
    return this.build();
  }

  // ═══════════════════════════════════════════════════
  //  LENDER-FACING ESCROW CERTIFICATE
  // ═══════════════════════════════════════════════════

  generateLenderCertificate(meta: Record<string, any>, docId: string, verificationToken: string): Uint8Array {
    const siteUrl = Deno.env.get("SITE_URL") || "https://trustlockpay.lovable.app";
    const verifyUrl = `${siteUrl}/verify/${verificationToken}`;
    const now = new Date();
    const expiresAt = meta.expires_at ? new Date(meta.expires_at) : new Date(now.getTime() + 90 * 24 * 60 * 60 * 1000);

    this.newPage();

    // ─── Premium Header ───────────────────────────
    this.drawRect(0, 800, 595, 42, `${this.brandGreen}`);
    this.drawText("TrustLock", 60, 812, 16, true);
    this.content.push("BT /F1 10 Tf 1 1 1 rg 160 814 Td (Escrow Platform) Tj 0 0 0 rg ET");
    this.content.push("BT /F1 8 Tf 1 1 1 rg 400 814 Td (LENDER CERTIFICATE) Tj 0 0 0 rg ET");

    // Title
    this.drawText("Lender-Facing Escrow Certificate", 60, 775, 16, true);
    this.drawText("Proof of Guaranteed Payment — For Third-Party Financiers", 60, 758, 9);
    this.drawLine(60, 748, 535, 748, 1.5, this.brandGreen);
    this.currentY = 730;

    // ─── Validity Banner ──────────────────────────
    this.drawRect(55, this.currentY - 4, 480, 22, "0.93 0.97 0.93");
    this.content.push(`BT /F2 9 Tf ${this.brandGreen} rg 65 ${this.currentY + 2} Td (VALID: ${now.toISOString().slice(0, 10)}  to  ${expiresAt.toISOString().slice(0, 10)}  |  90-Day Certificate) Tj 0 0 0 rg ET`);
    this.currentY -= 30;

    // ─── Certificate ID ──────────────────────────
    this.currentY = this.drawRow("Certificate ID", docId.slice(0, 8).toUpperCase(), this.currentY);
    this.currentY = this.drawRow("Verification Token", verificationToken.slice(0, 16) + "...", this.currentY);

    // ─── Transaction Details ─────────────────────
    this.drawSection("Escrow Transaction Details");
    this.currentY = this.drawRow("Transaction ID", meta.tx_id || docId, this.currentY);
    this.currentY = this.drawRow("Escrow Amount", `$${Number(meta.amount || 0).toLocaleString("en-US", { minimumFractionDigits: 2 })}`, this.currentY);
    this.currentY = this.drawRow("Escrow Status", "LOCKED — Funds Held in Trust", this.currentY);
    this.currentY = this.drawRow("Lock Date", now.toISOString().slice(0, 10), this.currentY);
    this.currentY = this.drawRow("Industry", meta.industry || "General", this.currentY);

    // ─── Full Disclosure: Parties ────────────────
    this.drawSection("Transaction Parties (Full Disclosure)");
    this.currentY = this.drawRow("Vendor (Seller)", meta.vendor_name || "N/A", this.currentY);
    this.currentY = this.drawRow("Buyer (Purchaser)", meta.buyer_name || "N/A", this.currentY);
    if (meta.buyer_email) {
      this.currentY = this.drawRow("Buyer Contact", meta.buyer_email, this.currentY);
    }

    // ─── Milestone Schedule ──────────────────────
    const milestones = meta.milestones;
    if (milestones && Array.isArray(milestones) && milestones.length > 0) {
      this.drawSection("Milestone Payment Schedule");
      for (let i = 0; i < milestones.length; i++) {
        const ms = milestones[i];
        const label = `Milestone ${i + 1}: ${ms.label || ms.title || "Phase " + (i + 1)}`;
        const pct = ms.percentage ? `${ms.percentage}%` : "N/A";
        const amt = meta.amount && ms.percentage ? `$${(Number(meta.amount) * Number(ms.percentage) / 100).toFixed(2)}` : "";
        this.currentY = this.drawRow(label, `${pct}  ${amt}`, this.currentY);
        if (this.currentY < 100) {
          this.newPage();
          this.currentY = 750;
        }
      }
    }

    // ─── Blockchain Verification ─────────────────
    this.drawSection("Blockchain Verification");
    if (meta.blockchain_tx_hash) {
      this.currentY = this.drawRow("Polygon TX Hash", meta.blockchain_tx_hash, this.currentY);
      this.currentY = this.drawRow("Verify on Polygonscan", `polygonscan.com/tx/${meta.blockchain_tx_hash}`, this.currentY);
    } else {
      this.currentY = this.drawRow("Chain Status", "Pending Anchor — Will be anchored to Polygon", this.currentY);
    }

    // ─── QR Verification ─────────────────────────
    this.drawSection("Online Verification");
    this.currentY -= 5;
    const qrLines = [
      "Lenders can independently verify this certificate at:",
      verifyUrl,
      "",
      "This URL provides real-time escrow status (locked, released,",
      "or disputed) without requiring a TrustLock account.",
    ];
    for (const line of qrLines) {
      this.drawText(line, 60, this.currentY, line === verifyUrl ? 9 : 10, line === verifyUrl);
      this.currentY -= 16;
    }

    // ─── Legal Certification ─────────────────────
    if (this.currentY < 180) {
      this.newPage();
      this.currentY = 750;
    }
    this.drawSection("Certification Statement");
    this.currentY -= 5;
    const cert = [
      "This certificate confirms that the above funds have been received",
      "and locked in TrustLock escrow. The funds are held in trust and",
      "will be released to the vendor only upon verified completion of",
      "contractual milestones or by administrative ruling.",
      "",
      "Neither party may unilaterally withdraw escrowed funds. This",
      "document may be presented to third-party financiers as proof",
      "of guaranteed payment to support pre-production financing,",
      "trade credit, or working capital applications.",
      "",
      "This certificate is valid for 90 days from the date of issue.",
      "Lenders should verify current status using the URL above.",
    ];
    for (const line of cert) {
      this.drawText(line, 60, this.currentY, 9);
      this.currentY -= 14;
    }

    // ─── Footer ──────────────────────────────────
    this.drawLine(60, 50, 535, 50, 0.5, "0.8 0.8 0.8");
    this.drawText(`Certificate ID: ${docId}`, 60, 38, 7);
    this.drawText(`Generated by TrustLock  |  trustlockpay.lovable.app  |  ${now.toISOString().slice(0, 10)}`, 60, 28, 7);
    this.drawText("Retained for 7 years per compliance policy  |  Valid for 90 days", 60, 18, 7);

    return this.build();
  }

  // ═══════════════════════════════════════════════════
  //  PDF Binary Builder
  // ═══════════════════════════════════════════════════

  private build(): Uint8Array {
    this.finalizePage();

    let pdf = "%PDF-1.4\n";

    // Object 1: Catalog
    const catalogContent = `<< /Type /Catalog /Pages 2 0 R >>`;

    // Object 2: Pages (placeholder — we'll fill in Kids)
    const kids = this.pages.map((p) => `${p} 0 R`).join(" ");
    const pagesContent = `<< /Type /Pages /Kids [${kids}] /Count ${this.pages.length} >>`;

    // Object 3: Font Helvetica
    const font1Content = `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>`;

    // Object 4: Font Helvetica-Bold
    const font2Content = `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>`;

    // Build all objects with proper numbering
    const allObjects = [catalogContent, pagesContent, font1Content, font2Content, ...this.objects.map((o) => o)];

    const offsets: number[] = [];
    for (let i = 0; i < allObjects.length; i++) {
      offsets.push(pdf.length);
      pdf += `${i + 1} 0 obj\n${allObjects[i]}\nendobj\n`;
    }

    // Cross-reference table
    const xrefOffset = pdf.length;
    pdf += `xref\n0 ${allObjects.length + 1}\n`;
    pdf += `0000000000 65535 f \n`;
    for (const offset of offsets) {
      pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
    }

    // Trailer
    pdf += `trailer\n<< /Size ${allObjects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

    return new TextEncoder().encode(pdf);
  }
}

// ═══════════════════════════════════════════════════════════
//  REQUEST HANDLER
// ═══════════════════════════════════════════════════════════

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const body = await req.json();
    const { action } = body;

    if (!action) return json({ error: "action required" }, 400);

    const supabase = getSupabase();

    // ═══════════════════════════════════════════
    //  ACTION: generate — Generate PDF for a protection_document record
    // ═══════════════════════════════════════════
    if (action === "generate") {
      const { documentId } = body;
      if (!documentId) return json({ error: "documentId required" }, 400);

      // Fetch the document record
      const { data: doc, error: docErr } = await supabase
        .from("protection_documents")
        .select("*")
        .eq("id", documentId)
        .single();

      if (docErr || !doc) {
        return json({ error: "Document not found", details: docErr?.message }, 404);
      }

      // Already generated?
      if (doc.file_url && doc.generation_status === "generated") {
        return json({ success: true, fileUrl: doc.file_url, alreadyGenerated: true });
      }

      // Mark as generating
      await supabase
        .from("protection_documents")
        .update({ generation_status: "generating" })
        .eq("id", documentId);

      const meta = (doc.metadata as Record<string, any>) || {};
      const builder = new PDFBuilder();
      let pdfBytes: Uint8Array;

      switch (doc.document_type) {
        case "escrow_acknowledgement":
          pdfBytes = builder.generateEscrowAcknowledgement(meta, doc.id);
          break;
        case "pre_order_contract":
          pdfBytes = builder.generatePreOrderContract(meta, doc.id);
          break;
        case "aml_certificate":
          pdfBytes = builder.generateAMLCertificate(meta, doc.id);
          break;
        case "payout_reconciliation":
          pdfBytes = builder.generatePayoutReconciliation(meta, doc.id);
          break;
        case "dispute_evidence_package":
          pdfBytes = builder.generateDisputePackage(meta, doc.id);
          break;
        default:
          await supabase
            .from("protection_documents")
            .update({ generation_status: "failed" })
            .eq("id", documentId);
          return json({ error: `Unknown document type: ${doc.document_type}` }, 400);
      }

      // Upload to storage
      const filePath = `${doc.transaction_id || "general"}/${doc.document_type}_${doc.id}.pdf`;
      const { error: uploadErr } = await supabase.storage
        .from("protection-documents")
        .upload(filePath, pdfBytes, {
          contentType: "application/pdf",
          upsert: true,
        });

      if (uploadErr) {
        console.error("[generate-pdf] Upload failed:", uploadErr);
        await supabase
          .from("protection_documents")
          .update({ generation_status: "failed" })
          .eq("id", documentId);
        return json({ error: "Upload failed", details: uploadErr.message }, 500);
      }

      // Get public URL
      const { data: urlData } = supabase.storage
        .from("protection-documents")
        .getPublicUrl(filePath);

      const fileUrl = urlData?.publicUrl || filePath;

      // Update record
      await supabase
        .from("protection_documents")
        .update({
          file_url: fileUrl,
          generation_status: "generated",
        })
        .eq("id", documentId);

      return json({ success: true, fileUrl, documentType: doc.document_type });
    }

    // ═══════════════════════════════════════════
    //  ACTION: generate_batch — Auto-generate pending docs
    // ═══════════════════════════════════════════
    if (action === "generate_batch") {
      const autoTypes = ["escrow_acknowledgement", "pre_order_contract", "aml_certificate"];
      const limit = body.limit || 20;

      const { data: pending, error: queryErr } = await supabase
        .from("protection_documents")
        .select("id, document_type")
        .eq("generation_status", "pending")
        .in("document_type", autoTypes)
        .limit(limit);

      if (queryErr) return json({ error: queryErr.message }, 500);
      if (!pending || pending.length === 0) {
        return json({ success: true, generated: 0, message: "No pending documents" });
      }

      let generated = 0;
      let failed = 0;
      const functionUrl = `${Deno.env.get("SUPABASE_URL")}/functions/v1/generate-pdf`;

      for (const doc of pending) {
        try {
          const res = await fetch(functionUrl, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")}`,
            },
            body: JSON.stringify({ action: "generate", documentId: doc.id }),
          });
          const result = await res.json();
          if (result.success) generated++;
          else failed++;
        } catch {
          failed++;
        }
      }

      return json({ success: true, generated, failed, total: pending.length });
    }

    // ═══════════════════════════════════════════
    //  ACTION: status — Check generation stats
    // ═══════════════════════════════════════════
    if (action === "status") {
      const { count: pending } = await supabase
        .from("protection_documents")
        .select("*", { count: "exact", head: true })
        .eq("generation_status", "pending");

      const { count: generated } = await supabase
        .from("protection_documents")
        .select("*", { count: "exact", head: true })
        .eq("generation_status", "generated");

      const { count: failed } = await supabase
        .from("protection_documents")
        .select("*", { count: "exact", head: true })
        .eq("generation_status", "failed");

      return json({
        pending: pending || 0,
        generated: generated || 0,
        failed: failed || 0,
        total: (pending || 0) + (generated || 0) + (failed || 0),
      });
    }

    return json({ error: `Unknown action: ${action}` }, 400);
  } catch (err: any) {
    console.error("[generate-pdf] Error:", err);
    return json({ error: err.message }, 500);
  }
});
